# Comme un langage, la syntaxe du logiciel docker-compose évolue
version: "3.3"

# un service est un conteneur
services: 
  # nom du service
  bdd:
    # image du conteneur
    # image: mysql
    image: mysql:5.7.27
    # variables d'environnement à injecter
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    # mapping des ports de l'os hôte avec le conteneur
    ports:
      - 11800:3306
    # un volume permet la persistance des données
    # permet de lier les répertoires de l'hôte avec le conteneur
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      